### PR TITLE
Pacheck po ng setContentView(R.layout.activity_main);, hindi po gumag…

### PR DESCRIPTION
**Pull request by crlmrqz**
…ana nakalagay po sa error cannot resolve symbol R

### CODE REVIEW

**Comment by simone123** [comment]
re open mo lang. android studio mo.

**Comment by manalilib** [comment]
@crlmrqz , did @simone123's suggestion work?

**Comment by crisostomodaryljhayc** [comment]
sir @manalilib  ok na po working na, just updated my sdk from 23 to 24 restarted also the android studio

**Comment by manalilib** [comment]
Good to know @crisostomodaryljhayc , how about yours @crlmrqz ? help each other guys.

**Pull request closed without merging**
